### ISSUE TITLE
Add a color picker when unable to get background color

### ISSUE THREAD

**Issue by mfaure** [Tanaguru/Contrast-Finder-Firefox#9]
... like the one from Colorzilla

Or browse the list of [color picker addons available for Firefox](https://addons.mozilla.org/fr/firefox/tag/color%20picker)
or:

https://addons.mozilla.org/en-US/firefox/addon/colorpick-eyedropper/?src=search
https://addons.mozilla.org/en-US/firefox/addon/colorzilla/?src=search
https://addons.mozilla.org/en-US/firefox/addon/rainbow-color-tools/?src=search
https://addons.mozilla.org/en-US/firefox/addon/colorpicker/?src=search
https://addons.mozilla.org/en-US/firefox/addon/color-pickers/?src=search
https://addons.mozilla.org/en-US/firefox/addon/firepicker/?src=search

**Comment by lingua** [comment]
The color picker is now available with the v0.3 Tanaguru Contrast-Finder extension !
